[tool.poetry]
name = "betterconf"
version = "2.1"
description = "Minimalistic Python library for your configs."
authors = ["prostomarkeloff"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/prostomarkeloff/betterconf"
repository = "https://github.com/prostomarkeloff/betterconf"
documentation = "https://github.com/prostomarkeloff/betterconf"
keywords = ["configs", "config", "env", ".env"]
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pre-commit = "^1.20.0"
mypy = "^0.761"
pytest = "^5.3.2"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
